### ISSUE TITLE
appelli ai quali si è prenotati CFU sempre a 0

### ISSUE THREAD

**Issue by mattmezza** [myunimol/api#11]
bug in estrazione cfu per appelli prenotati, pare che i cfu siano sempre 0... Perché?

**Comment by GiusWhite** [comment]
C'è un bel problema. Nella pagina degli appelli prenotati non c'è nessuna informazione ai CFU.
Quel 0 che viene visualizzato è semplicemente il valore di default che viene assegnato all'oggetto ExamSession.
Più precisamente, nell'extractor degli appelli a cui ci si è prenotati (ma anche negli appelli disponibili), non c'è nessuna assegnazione per i CFU, quindi nel Json viene restituito il valore di default.

**Comment by mattmezza** [comment]
Ottimo... Credo dunque che questa informazione vada cancellata da webapp,
api e app mobile. Confermi?

**Comment by GiusWhite** [comment]
I CFU potrebbero essere presi da altre sezioni chiamando altre api e facendo una ricerca. Questo però comporterebbe un aumento del tempo per la risposta enorme.

**Comment by mattmezza** [comment]
ehm... credo sia meglio fare a meno di tale informazione a questo punto... Si genererebbe una cascata di accessi al network assurdi in cui se una cosa va male sono cazzi.
Procediamo alla rimozione di tale informazione da tutta la piattaforma.
