### ISSUE TITLE
Libretto: date di verbalizzazione per esami non sostenuti

### ISSUE THREAD

**Issue by mattmezza** [myunimol/api#9]
**(da una issue aperta da @intersimone999 nel progetto android)**

Bisogna sistemare le seguenti cose:
- gli esami non verbalizzati compaiono come verbalizzati oggi
- il giudizio degli esami verbalizzati dovrebbe essere vuoto (invece appaiono scritte come "giudizio") 

[...]

:+1:

**Comment by intersimone999** [comment]
Sistemato 👍
